admin_email: support@blogtexts.com # must be a SenderSignature inside Postmark.com
admin_phone_number: '5558675309'
aws_access_key_id: "AK_INSERT_HERE"
aws_secret_access_key: "INSERT_HERE"
company_name: Blog Texts
postmark_api_token: xxxx-yyy-zzzz
sms_server: https://your-sms-server.com # create free: https://github.com/founderhacker/textbelt_deployable
development:
  base_url: http://localhost:3000
  stripe_secret_key: sk_test_asdfasdfasdf
  stripe_product_price_id: price_1asdfasdf
production:
  base_url: https://blogtexts.com
  stripe_secret_key: sk_live_asdfasdfasdf
  stripe_product_price_id: price_1asdfasdf
